print("KRISHAND INDONESIA")
print("Jakarta Selatan - Indonesia")
print("------------------------------------------------------------------------------------------")
print("                                 I N V O I C E                                            ")
print("Kepada Yth.                                               No.             :FT./003/01/2008 ")
print("PT ISM BOGOSARI FLOUR JAKARTA                             Tanggal         :30/01/2008      ")
print("Jl. Raya Cilincing, Tanjung Priok                         Mata uang       :IDR             ")
print("Jakarta Utara - 14110                                     No. PO          :PO-0001/01/2008 ")
print("                                                          Tgl.PO          :25/01/2008      ")
print("                                                          Tgl Jatuh Tempo :13/02/2008      ")
print("------------------------------------------------------------------------------------------")